# Usa una imagen base de Python
FROM python:3.8

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios para la aplicación
COPY . .

# Actualiza los paquetes e instala las dependencias
RUN apt-get update && \
    pip install --no-cache-dir -r requirements.txt

# Expone el puerto donde correrá la aplicación Dash
EXPOSE 8050

# Comando para iniciar la aplicación Dash
CMD ["python", "app.py"]
