# Utilizar una imagen base de Python 3.8
FROM python:3.8

# Instalar cron y vim (opcional)
RUN apt-get update && apt-get -y install cron vim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo de dependencias y luego instalar las dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el script principal de la aplicación, el archivo crontab, y el script de inicio
COPY app.py .
COPY crontab /etc/cron.d/crontab
COPY start_app.sh .

# Dar permisos correctos al archivo de crontab y cargarlo en cron
RUN chmod 0644 /etc/cron.d/crontab
RUN crontab /etc/cron.d/crontab

# Dar permisos de ejecución al script de inicio
RUN chmod +x /app/start_app.sh

# Ejecutar el script de inicio como el comando principal
CMD ["/app/start_app.sh"]
