version: '3.8'

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: dockerfile-db
    environment:
      POSTGRES_DB: iotplant
      POSTGRES_USER: simon
      POSTGRES_PASSWORD: simon123
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - middleware-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile-app
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: simon
      POSTGRES_PASSWORD: simon123
      POSTGRES_DB: iotplant
    networks:
      - middleware-network

networks:
  middleware-network:
    driver: bridge
