# Utilizar una imagen base de Python 3.10
FROM python:3.10

# Instalar cron y vim (opcional)
RUN apt-get update && apt-get -y install cron vim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo de dependencias y luego instalar las dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el archivo de crontab al directorio de cron del contenedor
COPY crontab /etc/cron.d/crontab

# Copiar el script principal de la aplicación
COPY app.py /app/app.py

# Dar permisos correctos al archivo de crontab y cargarlo en cron
RUN chmod 0644 /etc/cron.d/crontab
RUN /usr/bin/crontab /etc/cron.d/crontab

# Ejecutar cron como proceso principal del contenedor
CMD ["cron", "-f"]
