# Utilizar la imagen oficial de PostgreSQL como base
FROM postgres:13

# Variables de entorno para PostgreSQL
ENV POSTGRES_DB=iot_data
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Exponer el puerto de PostgreSQL
EXPOSE 5432
